### ISSUE TITLE
English Translation & Dash docset

### ISSUE THREAD

**Issue by AndreyZarembo** [strongself/The-Book-of-VIPER#2]
Надо запилить ветку English, а потом собрать документацию в Dash
https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset
https://kapeli.com/docsets

**Comment by Siroque** [comment]
Готов поспособствовать в переводе на немецкий если есть такая цель/желание

**Comment by etolstoy** [comment]
@Siroque Цели не было, но почему бы и нет :)

**Comment by akaralar** [comment]
I don't know Russian but I would like to read this, so 👍 for English translations :)

**Comment by frimoldi** [comment]
Is there any plan about translating this into English ?

**Comment by etolstoy** [comment]
@frimoldi - yes, I think of finishing the Russian and English versions of the book this year. You can track current progress in a separate branch - https://github.com/rambler-ios/The-Book-of-VIPER/tree/english.

**Comment by akaralar** [comment]
@etolstoy looking at your username makes me expect something literary :) looking forward to it, thanks for the effort!
