### ISSUE TITLE
Добавить примеры кода к статье про композицию модулей

### ISSUE THREAD

**Issue by Koshub** [strongself/The-Book-of-VIPER#23]
Можете добавить примеры кода, особенно в часть про составные модули? Хотя-бы псевдокоду или описание протоколов. То описание, что там есть, мне кажется, не достаточно для понимания. Каким образом происходит декаплинг супермодуля от чайлдов если таковой имеет место? Каким образом передаются параметры между подмодулями? Каким образом настраивается модуль, который инстанцируется вместе с сабвью, расположенного на вью другого модуля? Так же может сложится впечатление, что описанные модели слишком сложны. Мне кажется это не так, но это не достаточно явно по описанию. Спасибо.

**Comment by etolstoy** [comment]
@CognitiveDisson - Вадим, это по твоей части вопрос.

**Comment by bimawa** [comment]
Да я сейчас ткой велосипед на городил. Чет аж страшно стало... Чую не то как то :)

**Comment by NikKovIos** [comment]
Хотя бы укажите куда смотреть в https://github.com/rambler-digital-solutions/rambler-it-ios

Нужен пример с модулем в модуле

**Comment by CognitiveDisson** [comment]
В rambler-it для открытия подмодулей используем ViperMcFlurry. Примерами таких подмодулей может послужить [SearchReportsModule](https://github.com/rambler-digital-solutions/rambler-it-ios/tree/8424a33408b2ba31a0b8c6f1371cd264a651d504/conferences/Classes/PresentationLayer/UserStories/ReportsUserStory/Modules/SearchReportsModule) и  [TagModule](https://github.com/rambler-digital-solutions/rambler-it-ios/tree/8144601f408e31c86177d962fe3c281d5315b0ee/conferences/Classes/PresentationLayer/UserStories/LectureUserStory/Modules/TagModule). Как открывается SearchReportsModule можно увидеть в [SearchRouter](https://github.com/rambler-digital-solutions/rambler-it-ios/blob/8424a33408b2ba31a0b8c6f1371cd264a651d504/conferences/Classes/PresentationLayer/UserStories/ReportsUserStory/Modules/SearchModule/Router/SearchRouter.m).
