### ISSUE TITLE
Необходимо перенести содержание из WIKI в файлы

### ISSUE THREAD

**Issue by AndreyZarembo** [strongself/The-Book-of-VIPER#3]
Необходимо перенести содержание из WIKI в файлы, чтобы можно было выгрузить целиком все тексты и иметь к ним Offline доступ. Сейчас можно выгрузить только  Readme.md

**Comment by etolstoy** [comment]
Можно выгрузить отсюда: https://github.com/rambler-ios/The-Book-of-VIPER.wiki.git

**Comment by AndreyZarembo** [comment]
Смержили ветку с файлами
