### ISSUE TITLE
Viper + Mediator  передача данных между модулями

### ISSUE THREAD

**Issue by eastari** [strongself/The-Book-of-VIPER#31]
Иногда, когда коммуникации между модулями сложные (запутанные) можно использовать для передачи данных между модулями
паттерн Mediator https://github.com/ochococo/Design-Patterns-In-Swift  только вместо message: String   -   (имя получателя, Any) ,
а презенторы наследуются от MessageMediator 
Вопрос - отвечает ли это духу viper  (есть ли здесь опасности) ? Все работает и очень хорошо - но есть наследование  ? За ранее спасибо, Евгений

**Comment by eastari** [comment]
по аналогии с примером по ссылке презенторы наследуются от  class Colleague

**Comment by etolstoy** [comment]
А можете прислать uml-диаграмму получившейся системы классов?
