### ISSUE TITLE
Any plan to translate this great work into English?

### ISSUE THREAD

**Issue by nandin-borjigin** [strongself/The-Book-of-VIPER#35]
I can't read Russian, but as the repo-introduction says, this is one and the only one VIPER book and the catalog(I googled them) indicates that this book is great. I tried to consume it with Google translation and found it's impractical. I feel pity that most of the developers who can't read Russian will miss this nice book. 

Do you guys have any plan to port it to English (as most of the developers can read English)? I know this is too much to ask, but still please :)

**Comment by novixon** [comment]
Hi @Nandiin ,

Thanks for your question!  As you can see there are several requests for translation our book to English. That' why we want to resolve this issue as soon as possible.

I can't tell you the exact dates but the work is already in progress. Feel free to contribute to The Book when the English version will be ready.

**Comment by novixon** [comment]
@Nandiin ,

You can also see the progress here: 
https://github.com/rambler-ios/The-Book-of-VIPER/tree/english

**Comment by nandin-borjigin** [comment]
Wow, thanks! 👍
