### ISSUE TITLE
Пример работы NSFetchedResultsController в VIPER

### ISSUE THREAD

**Issue by kdev0** [strongself/The-Book-of-VIPER#38]
Могли бы вы добавить небольшой demo-проект(можно и на swift), показывающий работу NSFetchedResultsController в VIPER? А то из статьи не особо понятно, как происходит формирование CacheTransactionBatch(как строится очередь операция для insert, update, ...) и что представляет из себя CacheRequest.  
И как обрабатываются операции, например, когда прилетит update для еще не созданной записи?

**Comment by etolstoy** [comment]
@kdev0 в ближайшее время не обещаю, сейчас активно ведем работу над завершением самой книги. После этого возьмем в работу.

**Comment by kdev0** [comment]
@etolstoy, спасибо, буду ждать. Как вариант, в книге можно подробнее расписать работу сабжа + описать все элементарные структуры, типа CacheRequest. Как и где они используются. Это уже бы помогло. А demo-проект уже после книги добавить.

**Comment by etolstoy** [comment]
@kdev0 добавил дополнительную информацию в статью.
