### ISSUE TITLE
Grammar Issues

### ISSUE THREAD

**Issue by AndreyZarembo** [strongself/The-Book-of-VIPER#5]
Please, post any grammar, punctuation or misspelling issues here as comments.
Pull request are welcome.

**Comment by dakeshi** [comment]
Hi. I make new PRs in #33 

It's awesome projects to help understand VIPER.
I'm not the native but I'd like to improve the documents to help someone.

In my case, it would be very helpful to translate the master repo documents with google translator.
To provide more info in english branch, this approach would be good.
Google translation results and fixing it later.
