### ISSUE TITLE
Пример взаимодействия с DataDisplayManager

### ISSUE THREAD

**Issue by krasnodar95** [strongself/The-Book-of-VIPER#57]
Недавно прочитал вашу книжку по Viper. Огромное спасибо за проделанную работу. У меня вопрос связанный с DataDisplayManager. В книжке эта тема затронута вскользь. Судя по схеме в главе "Структура viper-модуля", DDM должен быть связан только со View. У меня вопрос как тогда нужно подкидывать в него данные для отображения(я так понимаю что это те самые PONSO-объекты)? Нужно ли эти данные хранить в DDM? Хотелось бы увидеть более  развернутое объяснение. Спасибо:)

**Comment by etolstoy** [comment]
@krasnodar95 спасибо за вопрос! В общем виде DDM - это класс, реализующий два протокола, `UITableViewDataSource` и `UITableViewDelegate`. Есть два варианта его устройства:
- Для форм или списков с ограниченным количеством контента в DDM прокидываются модельки, из которых он генерирует view model'и для отображения и держит их у себя (как массив или `NITableViewModel` при использовании Nimbus).
- Для списков с большим количеством контента разумно вытаскивать данные по необходимости и не держать их в памяти - тогда DDM через View и Presenter запрашивает их у интерактора.

**Comment by krasnodar95** [comment]
- В первом случае есть схожесть с MVVM. В том плане что мы генерим ViewModel'ы. Насколько знаю MVVM запрещает вообще передавать модельки во View-слой, там вроде как надо что бы View работала только с ViewModel'ами. Тут получается смесь, мы вроде бы пользуемся модельками во View, а вот в случае с UITableView и UICollectionView начинаем пользоваться ViewModel'ами. Не улавливаю чистоту концепции. Ну это так, размышления. Еще касательно первого варианта такой вопрос: DDM сам должен заниматься преобразованием моделей в ViewModel'ы?
- Во втором случае хотел бы уточнить. Получается что у ViewController'а и у Presenter'а должны быть реализованы подобные методы:

`-(NSInteger) countOfObjects;`
`-(id)objectByIndex: (NSInteger *)index;`
И так до интерактора?

**Comment by etolstoy** [comment]
@krasnodar95 в этом случае под viewmodel понимаем обычные DTO, которые доставляют до ячеек данные, нужные им для отображения - так что MVVM здесь не при чем. В простых случаях DDM сам преобразует модели во view model'и, в более сложных - логика выносится в отдельный cellObjectFactory.
Во втором случае да - но семантика методов меняется в зависимости от конкретного слоя. Плюс в некоторых случаях цепочка может заканчиваться на презентере, который держит промежуточный стейт (к примеру, текущее количество элементов таблицы).

**Comment by krasnodar95** [comment]
@etolstoy Спасибо! Стало гораздо понятнее) В книге было бы неплохо уделить внимание этому вопросу. У нас ведь почти везде коллекции и таблицы)
