### ISSUE TITLE
Планируете ли описать архитектурный подход VIPER для Android?

### ISSUE THREAD

**Issue by rsdev-atk** [strongself/The-Book-of-VIPER#58]

**Comment by DevAlloy** [comment]
Ребята из Android отдела написали: https://habrahabr.ru/company/rambler-co/blog/277003/

**Comment by CROSP** [comment]
Для Android существует уже достаточное количество статей на эту тему. Гуглите "Android Clean Architecture" 

Вот несколько полезных ссылок по этой теме + ту которую предоставил @DevAlloy 
https://github.com/android10/Android-CleanArchitecture
http://luboganev.github.io/blog/clean-architecture-pt1/
http://five.agency/android-architecture-part-1-every-new-beginning-is-hard/

**Comment by etolstoy** [comment]
@rsdev-atk присоединяюсь ко ссылкам, приведенным выше. Мы пока не планируем агрегировать всю эту информацию в отдельную книгу.
