### ISSUE TITLE
Как обращаться с Алертами? 

### ISSUE THREAD

**Issue by NikKovIos** [strongself/The-Book-of-VIPER#59]
Какие у вас best practice для обращения с алертами? Оставлять ли их в контроллере?
Например у меня есть алерт, который предоставляет список языков, и позволяет выбрать один их них, а затем на основании этого изменить нечто во view. Поидее нужно передавать его по цепочке View-Presenter-Interactor. В интеракторе писать логику алерта, затем назад показывать во view. Затем.. вообщем как вы делаете обычно?)

Такой же вопрос относительно UIPickerViewDataSource - В DataDisplayManager или во ViewController?

**Comment by Sapozhnik** [comment]
У нас есть отдельный viper-модуль для алертов, с ним работаем обычно – создаем через router, обратная связь через moduleOutput (между презентерами). 

Для UIPickerViewDataSource я бы создал отдельный ДДМ.
