### ISSUE TITLE
english progress?

### ISSUE THREAD

**Issue by dpereira411** [strongself/The-Book-of-VIPER#61]
maybe you can create a Bountysource page so we can contribute with some money to help translate the book to english? :)

**Comment by CROSP** [comment]
@etolstoy  Вам еще требуется помощь в переводе на английский ? Мог бы помочь перевести несколько разделов.

**Comment by etolstoy** [comment]
@dpereira411 Thanks for your idea - the problem is not in money, but in the lack of time :) BTW, we're considering organizing a Boomstarter (russian Kickstarter) campaign to make paper edition of our book.

**Comment by dpereira411** [comment]
that would be great! thanks :)
