### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dron247** [strongself/The-Book-of-VIPER#70]
https://github.com/rambler-digital-solutions/The-Book-of-VIPER/blob/master/russian/compound-modules.md

опечатка в картинке "complicating debag",  правильно -  debug. Имеет смысл написать как о факте complicated debug, hard to debug

**Comment by etolstoy** [comment]
Thanks for the issue! @CognitiveDisson will you fix it?

**Comment by CognitiveDisson** [comment]
Fixed
