### ISSUE TITLE
Неправильная иллюстрация для раздела `Таблица с группами ячеек`

### ISSUE THREAD

**Issue by x0000ff** [strongself/The-Book-of-VIPER#73]
#### Глава
- [Простой vs Сложный модуль](https://github.com/strongself/The-Book-of-VIPER/blob/master/russian/compound-modules.md#Таблица-с-группами-ячеек)

#### Раздел
- [Таблица с группами ячеек](https://github.com/strongself/The-Book-of-VIPER/blob/master/russian/compound-modules.md#Таблица-с-группами-ячеек)

## Изображение

Неправильно | Неправильно с пометками
--------------|-------------
![](https://etolstoy.gitbooks.io/the-book-of-viper/content/assets/submodules.007.png) | ![submodules](https://cloud.githubusercontent.com/assets/1062240/22796876/eef95510-eeda-11e6-8682-4474c52ec2c3.png)

**Comment by CognitiveDisson** [comment]
Спасибо за issue.  Исправлю.

**Comment by x0000ff** [comment]
@CognitiveDisson, Я сейчас PR с исправлением сделаю 😉
