### ISSUE TITLE
Licensing (again)

### ISSUE THREAD

**Issue by Brain89** [strongself/The-Book-of-VIPER#8]
MIT license is not suitable in this situation. Using Creative Commons «Attribution-NonCommercial» is a more correct. 
Links
- http://creativecommons.org/licenses/by-nc/4.0/
- http://creativecommons.org/licenses/by-nc/4.0/legalcode

The LICENSE file should contain something like "The Book of VIPER by RAMBLER&Co iOS Team is licensed under a Creative Commons Attribution 4.0 International License".

**Comment by etolstoy** [comment]
And once again, we need @mogol here

**Comment by mogol** [comment]
@Brain89 , thanks!
Lets add ShareAlike and use
http://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by etolstoy** [comment]
Добавил лицензию: https://github.com/rambler-ios/The-Book-of-VIPER/blob/master/LICENSE

**Comment by yas375** [comment]
@etolstoy would be nice to have the license formatted with new lines. Currently it's hard to read:
![2016-07-19_0916](https://cloud.githubusercontent.com/assets/217368/16957539/93daa7fa-4d91-11e6-89e8-4c2b2f756ee2.png)

Thanks in advance!

**Comment by etolstoy** [comment]
@yas375 готово!
